### ISSUE TITLE
Ensuring optimum security

### ISSUE THREAD

**Issue by poacher2k** [scott-wyatt/sails-stripe#4]
I am going to be implementing an extra step in `StripeController.js` that ensures "optimum security", as per [Stripe docs](https://stripe.com/docs/webhooks):

> For optimum security, you can confirm the event data with Stripe before acting upon it. To do so:
> 1. Parse the JSON data as above.
> 2. Grab the received Event object ID value.
> 3. Use the Event object ID in a retrieve event API call.
> 4. Take action using the returned Event object.

Should I add a pull request with this when I am complete?

As it makes for an extra request, perhaps this should be made optional?

**Comment by scott-wyatt** [comment]
That would be awesome!  This feature is in the Roadmap so yes, please do submit a pull request when complete. Here's how I personally think this feature should work.  The "Round Trip" mechanism should be for validation of the event only and not create/update/delete. That all said, it's your hard work and pull request, and please feel free to do what you believe is best.

**Comment by poacher2k** [comment]
Didn't see that it was in the roadmap! 

What I currently do is getting the event from Stripe, and if it exist, use the event data returned by the round trip to create and handle the event. We could only use the returned event for validation, but as the event returned for Stripe for _sure_ is safe to use - and should be identical - I think it's a good idea to use the event data from Stripe directly.

This is what I currently got:

```
// createEvent = the entire content of the "webhook"
// function as seen here:
// https://github.com/scott-wyatt/sails-stripe/blob/master/templates/StripeController.template.js#L11

var allParams = req.params.all();

if (!allParams.id) {
    return res.badRequest('An event ID is required when sending events to WebHook');
}

if (enableExtraSecurity) {
    stripe.events.retrieve(allParams.id, function(err, event) {
        if (err) return res.negotiate(err);

        createEvent(event);
    });
} else {
    createEvent(allParams);
}
```

Perhaps I misunderstood what you mean about using it for validation only? =)

**Comment by scott-wyatt** [comment]
I like where you are heading with this.  I have an Idea though.  I think, this validation should be part of Sails' model lifecycle events and while it is slower, I think required is best (even Stripe recommends this like you pointed out).  
Here's what I'm thinking:
Webhook hits StripeController.  The first thing that happens is that the controller does a quick check to see if the event is already stored (via the count of the model which is typically very fast however it is a race condtion, luckily Stripe waits an hour between trying to resend the request).  If the event has been stored, it issues an Event.create.  I think that we should make the validation request part of the lifecycle hook "beforeCreate".  That way, we can make sure it's not a bogus request before inserting it into the database.  If the validation fails, it throws an error, and that cancels the rest of the event from StripeController, if the validation passes then it continues as normal. Thoughts?

**Comment by poacher2k** [comment]
That sounds like a great idea!

**Comment by scott-wyatt** [comment]
Closing this issue to carry on with the #5 pull request commenting
