### ISSUE TITLE
 Error: An Event ID is required

### ISSUE THREAD

**Issue by cappern** [scott-wyatt/sails-stripe#7]
I think I have everything set up right, any ideas what this means?
```
Details:  Error: An Event ID is required { created: Wed Jan 18 2012 02:24:38 GMT+0000 (UTC),
  livemode: false,
  id: 'evt_00000000000000',
  type: 'charge.succeeded',
  object: 'event',
  request: null,
  pending_webhooks: '1',
  api_version: '2017-01-27',
  data: 
   { object: 
      { id: 'ch_00000000000000',
        object: 'charge',
        amount: 500000,
        amount_refunded: 0,
```

**Comment by scott-wyatt** [comment]
Was this coming from a stripe webhook?

**Comment by cappern** [comment]
Yes, from the sails console right after an avent is received on the web hook route from stripe.

**Comment by scott-wyatt** [comment]
Hmmm, the best I can think of is your database might be rejecting the id as a string?

**Comment by cappern** [comment]
I'm currently using the local sails database, I will try it out with mongodb later and report back. Thanks.
